### ISSUE TITLE
DISABLE_WEBSOCKET_SSL=OFF build error at ss-sdk 2.0.2

### ISSUE THREAD

**Issue by yuan0258** [alexa/alexa-smart-screen-sdk#24]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Here is my build option
cmake \
-DCMAKE_PREFIX_PATH=../sdk-install \
-DWEBSOCKETPP_INCLUDE_DIR=$HOME/sdk_folder/third-party/websocketpp-0.8.1 \
-DDISABLE_WEBSOCKET_SSL=OFF \
-DGSTREAMER_MEDIA_PLAYER=ON \
-DCMAKE_BUILD_TYPE=RELEASE \
-DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=/home/pi/sdk_folder/third-party/portaudio/lib/.libs/libportaudio.a \
-DPORTAUDIO_INCLUDE_DIR=$HOME/sdk_folder/third-party/portaudio/include/ \
-DAPL_CORE=ON \
-DAPLCORE_INCLUDE_DIR=$HOME/sdk_folder/apl-core-library/aplcore/include \
-DAPLCORE_LIB_DIR=$HOME/sdk_folder/apl-core-library/build/aplcore \
-DYOGA_INCLUDE_DIR=$HOME/sdk_folder/apl-core-library/build/yoga-prefix/src/yoga \
-DYOGA_LIB_DIR=$HOME/sdk_folder/apl-core-library/build/lib \
../alexa-smart-screen-sdk

Build error log as below
[ 57%] Building CXX object modules/Alexa/SampleApp/src/CMakeFiles/SampleApp.dir/SampleApplication.cpp.o
/home/pi/avs-1.19/alexa-smart-screen-sdk/modules/Alexa/SampleApp/src/SampleApplication.cpp: In member function ‘bool alexaSmartScreenSDK::sampleApp::SampleApplication::initialize(const std::vector<std::__cxx11::basic_string<char> >&, const string&, const string&, std::shared_ptr<alexaClientSDK::avsCommon::sdkInterfaces::diagnostics::DiagnosticsInterface>)’:
/home/pi/avs-1.19/alexa-smart-screen-sdk/modules/Alexa/SampleApp/src/SampleApplication.cpp:699:5: error: ‘m_webSocketServer’ was not declared in this scope
     m_webSocketServer->setCertificateFile(sslCaFile, sslCertificateFile, sslPrivateKeyFile);
     ^~~~~~~~~~~~~~~~~
/home/pi/avs-1.19/alexa-smart-screen-sdk/modules/Alexa/SampleApp/src/SampleApplication.cpp:699:5: note: suggested alternative: ‘webSocketServer’
     m_webSocketServer->setCertificateFile(sslCaFile, sslCertificateFile, sslPrivateKeyFile);
     ^~~~~~~~~~~~~~~~~
     webSocketServer

Here is my solution as below. Please help to check does this change is ok or not
=================================
diff --git a/modules/Alexa/SampleApp/src/SampleApplication.cpp b/modules/Alexa/SampleApp/src/SampleApplication.cpp
index 8562c58..f2c20ab 100644
--- a/modules/Alexa/SampleApp/src/SampleApplication.cpp
+++ b/modules/Alexa/SampleApp/src/SampleApplication.cpp
@@ -696,7 +696,7 @@ bool SampleApplication::initialize(
     std::string sslPrivateKeyFile;
     sampleAppConfig.getString(WEBSOCKET_PRIVATE_KEY, &sslPrivateKeyFile);

-    m_webSocketServer->setCertificateFile(sslCaFile, sslCertificateFile, sslPrivateKeyFile);
+    webSocketServer->setCertificateFile(sslCaFile, sslCertificateFile, sslPrivateKeyFile);
 #endif

     m_guiClient = gui::GUIClient::create(webSocketServer, miscStorage);

## What is the expected behavior?

Build ok
## What behavior are you observing?

Build error

## Provide the steps to reproduce the issue, if applicable:

Build with avs-1.19 with -DDISABLE_WEBSOCKET_SSL=OFF

### What version of the AVS Device SDK are you using?
      <1.19>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [*] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [* ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by jason-amzn** [comment]
hello, thank you for reaching out!

It appears to be a typo, and the solution you illustrated should resolve the issue. 

Please reach out again if you encounter more issues.

**Comment by jason-amzn** [comment]
Closing this issue - please reopen if you encounter more errors.
